Scrape outdated revision of 2013 members table
everypolitician-scrapers/iceland-althing-wp pull request #1
Opened 2017-01-11 10:33 UTC by ondenman

We were losing Jón Þór Ólafsson in the data import as he was removed
from the 2013 table -- having been replaced by Ásta Guðrún Helgadóttir.

This commit scrapes the last revision of the 2013 table in which he appears.

## [Scraper Change checklist](https://github.com/everypolitician/everypolitician/wiki/Scraper-Change-checklist)
* [ ] 1. scraper is on Morph.io under the "everypolitician-scrapers" group?
* [ ] 2. scraper's GitHub "Website" link points at morph.io page?
* [ ] 3. scraper is set to auto-run?
* [ ] 4. scraper is archiving?
* [ ] 5. legislature has a scraper webhook set?

2017-01-12 11:29 UTC, tmtmtmtm requested changes
I'm a little hesitant about this approach generally, but as a quick win it _might_ be OK.

However, you're really doing two steps in one commit — one refactoring to extract a helper method, and then one to scrape a new page with that method. These should really be separated.

I'm also a little concerned by the inconsistency of scraping the Template directly here, but scraping the page that includes it in the 'normal' case. I'd suggest harmonising those (presumably by making both cases use the Template).

This code also doesn't pass `rubocop`. I've turned on automatic travis checking (it's fine to rebase this over master, as you'll need to split commits up etc anyway)

2017-01-12 11:29 UTC, tmtmtmtm commented on scraper.rb
> +  '2013' => 'https://en.wikipedia.org/w/index.php?title=Template:MembersAlthing2013&direction=prev&oldid=714280236'
I don't think you need the version with `direction=prev` here.

2017-01-24 20:18 UTC, tmtmtmtm requested changes
You might want to consider making https://github.com/everypolitician-scrapers/iceland-althing-wp/pull/1/commits/cce3704f36a1021baec4c8326e92f36e1cee092f a PR of its own — there's really no need to couple that to the other changes here.

2017-01-24 20:18 UTC, tmtmtmtm commented on scraper.rb
> +    members = page.members.each { |m| m[:term] = term }
I realise that this code pre-existed, but as you're now wrapping this up into a new method, it's probably worth bringing this in line with how we tend to do this now, as this idiom is a bit confusing.  This scraper as a whole is still quite a mess, and we don't need to fix it all up in one shot, but when working on a particular piece of good, it's good to bring it in line with our current approach where that's sensible, and here that looks quite simple to do.

2017-01-24 20:18 UTC, tmtmtmtm commented on scraper.rb
> +scrape_new_format_terms(old_revisions)
splitting these out to two lists is nice, but I think I'd combine this into a single function call to more clearly show that it's just doing the same thing for all of them.

2017-01-26 13:05 UTC, ondenman commented
Closing in favour of https://github.com/everypolitician-scrapers/iceland-althing-wp/pull/3

2017-01-26 13:05 UTC, closed without merging